// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhwakmhpxmsxfvxqkyai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlod2FrbWhweG1zeGZ2eHFreWFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NDQ0MjcsImV4cCI6MjA3MTIyMDQyN30.s2npuqLPPc9CfjnXvnsUUkQ4HZvYD71Jc9DjqKtyKUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});